016/master
ga-wdi-boston/rails-api-diagnostic pull request #107
Opened 2017-02-06 19:15 UTC by BenGitsCode

Update from diagnostic template.

2017-02-07 23:39 UTC, jrhorn424 requested changes

2017-02-07 23:39 UTC, jrhorn424 commented on README.md
> +your responses are correct.
Comfort/clarity check is missing (around this line? double check me on this).

2017-02-07 23:39 UTC, jrhorn424 commented on README.md
Try to include changes like this in the previous commit next time. I consider things like this part of updating from template.

2017-02-08 00:16 UTC, jrhorn424 commented
Please address also my comments on #108 here, on this PR.

2017-02-08 00:55 UTC, jrhorn424 requested changes

2017-02-08 00:55 UTC, jrhorn424 commented on diagnostic.md
>  line? (3 bullet points)
In the solution, this line says (5 bullet points), here it only says (3 bullet points). Please address.

2017-02-08 01:35 UTC, BenGitsCode commented on diagnostic.md
>  line? (3 bullet points)
Ah, I'm sorry I missed that. Fixed in 3adac871a8eb5fa4406bc3a4311a798176745999

2017-02-08 01:53 UTC, jrhorn424 commented
Awesome commit message.

2017-02-08 01:54 UTC, merged